/**
 * @file main_example.c
 * @brief Basic example of using the DHT22 library for STM32
 * * Note: 
 * 1. Ensure you have configured a Timer (e.g., TIM11) to generate microsecond delays.
 * 2. Configure the corresponding GPIO pin in the DHT22.h file or via STM32CubeMX.
 */

#include "main.h"
#include "DHT22.h" // Include the DHT22 library

// Declare a variable to store sensor data
DHT22_Data_t EnvData;

// Declare configuration variables/functions (generated by STM32CubeMX)
extern TIM_HandleTypeDef htim11; 

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_TIM11_Init(void);

int main(void)
{
  // 1. Initialize the HAL system and System Clock
  HAL_Init();
  SystemClock_Config();

  // 2. Initialize GPIO and Timer
  MX_GPIO_Init();
  MX_TIM11_Init();

  // 3. Start the Timer (REQUIRED for the microsecond delay function in the library)
  HAL_TIM_Base_Start(&htim11);

  // Initialize default values for the data variable
  EnvData.Temperature = 0.0f;
  EnvData.Humidity = 0.0f;

  // Variable to store the last read time
  uint32_t last_read_time = 0;

  while (1)
  {
    // The DHT22 sensor requires at least a 2-second interval between reads
    if (HAL_GetTick() - last_read_time >= 2000) 
    {
        last_read_time = HAL_GetTick();
        
        // Call the read function, passing the address of the EnvData variable
        if (DHT22_Read(&EnvData) == 1) 
        {
            // Read SUCCESSFUL!
            // The temperature value is stored in: EnvData.Temperature
            // The humidity value is stored in: EnvData.Humidity
            
            // You can print to UART, display on an LCD, or transmit it here.
            // Example of printing via UART (if printf is configured):
            // printf("Temperature: %.1f *C, Humidity: %.1f %%\r\n", EnvData.Temperature, EnvData.Humidity);
        }
        else
        {
            // Read FAILED (Checksum error, no response, etc.)
            // Handle errors here (e.g., blink a warning LED)
        }
    }
    
    // Other tasks run normally within the while(1) loop
  }
}